# Generated by Django 5.1.7 on 2025-03-28 02:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "nik",
                    models.CharField(max_length=50, unique=True, verbose_name="NIK"),
                ),
                (
                    "email",
                    models.EmailField(max_length=50, unique=True, verbose_name="Email"),
                ),
                ("nama", models.CharField(max_length=200, verbose_name="Nama Lengkap")),
                (
                    "tempat_lahir",
                    models.CharField(max_length=50, verbose_name="Tempat Lahir"),
                ),
                ("tgl_lahir", models.DateField(verbose_name="Tanggal Lahir")),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        max_length=10,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "no_hp",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="No. HP"
                    ),
                ),
                (
                    "lokasi",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Lokasi Latihan",
                    ),
                ),
                (
                    "provinsi",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Provinsi"
                    ),
                ),
                (
                    "kabupaten",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kabupaten"
                    ),
                ),
                (
                    "kecamatan",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kecamatan"
                    ),
                ),
                (
                    "kelurahan",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kelurahan"
                    ),
                ),
                (
                    "unit_latihan",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Unit Latihan",
                    ),
                ),
                (
                    "pas_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/pas_photo",
                        verbose_name="Pas Photo",
                    ),
                ),
                (
                    "ktp",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/ktp",
                        verbose_name="KTP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anggota",
                "verbose_name_plural": "Anggota",
            },
        ),
    ]
