# Generated by Django 5.1.7 on 2025-03-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="thn_gabung",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tahun bergabung"
            ),
        ),
    ]
