# Generated by Django 5.1.7 on 2025-03-29 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IKT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('nomor_sertifikat', models.CharField(max_length=100, unique=True)),
                ('naik_ke_tingkat', models.CharField(blank=True, choices=[('putih', 'Putih'), ('kuning', 'Kuning'), ('merah', 'Merah'), ('biru', 'Biru'), ('coklat', 'Coklat'), ('hitam', 'Hitam')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('menunggu', 'Menunggu'), ('disetujui admin wilayah', 'Disetujui Admin Wilayah'), ('disetujui admin pac', 'Disetujui Admin Pac'), ('ditolak', 'Ditolak')], default='menunggu', max_length=50, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='sertifikat/', verbose_name='File sertifikat sebelumnya')),
                ('alasan_penolakan', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ikt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('nomor_sertifikat', models.CharField(max_length=100, unique=True)),
                ('diterbitkan_oleh', models.CharField(max_length=255)),
                ('tanggal_terbit', models.DateField()),
                ('tingkat', models.CharField(choices=[('putih', 'Putih'), ('kuning', 'Kuning'), ('merah', 'Merah'), ('biru', 'Biru'), ('coklat', 'Coklat'), ('hitam', 'Hitam')], max_length=10)),
                ('file_sertifikat', models.FileField(blank=True, null=True, upload_to='sertifikat/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sertificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
