# Generated by Django 5.1.7 on 2025-04-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_ikt_sertifikat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='members',
            name='alamat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat Rumah'),
        ),
        migrations.AddField(
            model_name='members',
            name='nama_pelatih',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pelatih'),
        ),
    ]
