# Generated by Django 5.1.7 on 2025-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_members_lokasi_members_alamat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='kabupaten_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten'),
        ),
        migrations.AddField(
            model_name='members',
            name='kecamatan_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='members',
            name='kelurahan_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kelurahan'),
        ),
        migrations.AddField(
            model_name='members',
            name='provinsi_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi'),
        ),
    ]
