# Generated by Django 5.1.7 on 2025-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_members_kabupaten_latihan_members_kecamatan_latihan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_pelatih',
            field=models.BooleanField(default=False, verbose_name='Pelatih'),
        ),
        migrations.AlterField(
            model_name='members',
            name='kabupaten_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten Latihan'),
        ),
        migrations.AlterField(
            model_name='members',
            name='kecamatan_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan Latihan'),
        ),
        migrations.AlterField(
            model_name='members',
            name='kelurahan_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kelurahan Latihan'),
        ),
        migrations.AlterField(
            model_name='members',
            name='provinsi_latihan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi Latihan'),
        ),
    ]
