# Generated by Django 3.2 on 2025-04-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20250425_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_pelatih',
        ),
    ]
