# Generated by Django 3.2 on 2025-04-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_members_is_pelatih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='ktp',
            field=models.ImageField(default=1, upload_to='members/ktp', verbose_name='KTP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='pas_photo',
            field=models.ImageField(default=1, upload_to='members/pas_photo', verbose_name='Pas Photo'),
            preserve_default=False,
        ),
    ]
