# Generated by Django 3.2 on 2025-04-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20250427_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.members'),
        ),
    ]
