# Generated by Django 5.1.7 on 2025-03-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                default="admin",
                max_length=50,
                verbose_name="Role",
            ),
        ),
    ]
