# Generated by Django 5.1.7 on 2025-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accountuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kabupaten'),
        ),
    ]
