# Generated by Django 5.1.7 on 2025-04-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountuser_kabupaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('pac', 'Pac')], default='admin', max_length=50, verbose_name='Role'),
        ),
    ]
