# Generated by Django 5.1.7 on 2025-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_accountuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('pac', 'Pac'), ('pc', 'Pc')], default='admin', max_length=50, verbose_name='Role'),
        ),
    ]
