# Generated by Django 3.2 on 2025-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_accountuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('santri', 'Santri'), ('pelatih cabang', 'Pelatih Cabang'), ('pac', 'Pac'), ('pc', 'Pc')], default='admin', max_length=50, verbose_name='Role'),
        ),
    ]
